Allow retry on authentication timed out.
EventStore/EventStoreDB-Client-Dotnet-Legacy pull request #11
Opened 2021-08-13 17:11 UTC by YoEight

This patch allows the client to restart the connection process from scratch if the authentication process is timed out. The retry limit is tied to the connection `MaxRetries` setting. If the client goes above that limit, then the workflow continues to the identification phase. We might consider closing the connection for good if it happens though.

All this new behaviour will be gated behind a new setting so it doesn't conflict with the previous connection workflow.

2021-08-18 12:17 UTC, hayley-jean requested changes

2021-08-19 06:20 UTC, YoEight commented on src/EventStore.ClientAPI/ConnectionSettingsBuilder.cs
> +		public ConnectionSettingsBuilder AuthenticationRetryOnTimeout() {
Done

2021-08-19 10:33 UTC, thefringeninja approved these changes

2021-08-23 14:24 UTC, Lougarou approved these changes
LGTM

2021-08-24 11:27 UTC, hayley-jean approved these changes

2021-08-24 11:27 UTC, hayley-jean commented on src/EventStore.ClientAPI/Internal/EventStoreConnectionLogicHandler.cs
> +							// We retry a fresh connection if the authentication phase has failed.
```suggestion
							// We resend the authentication package if the authentication phase has failed.
```

2021-08-25 10:30 UTC, thefringeninja approved these changes

2021-08-25 15:19 UTC, merged