Update README with TCP deprecation notes
EventStore/EventStoreDB-Client-Dotnet-Legacy pull request #81
Opened 2024-03-04 23:32 UTC by rsowald

2024-03-04 23:36 UTC, cdevarenne submitted a review, later dismissed

2024-03-05 13:59 UTC, rmalik-es requested changes

2024-03-05 13:59 UTC, rmalik-es commented on README.md
> +We attempt to do our best to ensure that the history remains clean and to do so, we generally ask contributors to squash their commits into a set or single logical commit.
```suggestion
To maintain a clean history, we ask contributors to squash their commits into one or a few cohesive commits.
```

2024-03-05 13:59 UTC, rmalik-es commented on README.md
> +If you're looking for the recommended .NET gRPC client, check the [EventStore-Client-Dotnet](https://github.com/EventStore/EventStore-Client-Dotnet) repo.
```suggestion
For the preferred .NET gRPC client, visit the [EventStore-Client-Dotnet](https://github.com/EventStore/EventStore-Client-Dotnet) repository.
```

2024-03-08 16:27 UTC, rmalik-es commented on README.md
> +Interact with the Event Store and event sourcing Communities on the Event Store [Discuss](https://discuss.eventstore.com/) or [Discord](https://discord.gg/Phn9pmCw3t) forum.
```suggestion
Interact with the Event Store and event sourcing communities on the Event Store [Discuss](https://discuss.eventstore.com/) or [Discord](https://discord.gg/Phn9pmCw3t) forum.
```

2024-03-08 18:49 UTC, Hiyatei approved these changes
LGTM, thanks for updating links on the way through!

2024-03-08 18:57 UTC, cdevarenne approved these changes

2024-03-11 10:41 UTC, rmalik-es approved these changes

2024-03-11 17:03 UTC, thefringeninja approved these changes

2024-03-11 17:03 UTC, merged